### ISSUE TITLE
Die komplette Konfiguration funktioniert nicht mehr

### ISSUE THREAD

**Issue by Speedbreaker12** [iobroker-community-adapters/ioBroker.radar2#101]
Es ist mir bis jetzt nie aufgefallen, da ich keine neuen Geräte hinzufügen wollte, aber ich glaube vor ein paar Versionen ist die Konfig komplett kaputt gegangen. 
Es geht garnichts mehr mit dem Admin 5 und aktuellem JS-Controller 3.3.15.

Die Konfiguration wird nicht geladen und man kann auch keine neuen Geräte hinzufügen. Auch der Speichern und schliessen Button funktioniert nicht. Es passiert einfach nichts.

Wie man sieht ist die config komplett leer. 
![radar2_1](https://user-images.githubusercontent.com/18654629/129188965-372977a6-d7b1-4dbf-9a72-ce9870b7c008.JPG)

Die Daten sind aber da:
![radar2_2](https://user-images.githubusercontent.com/18654629/129189171-7865de40-c8fb-48e7-8945-41945418ff56.JPG)

Ich bin gerade mal WEIT WEIT zurück auf die 1.2.5 gegangen und siehe da, die Daten sind da. Also muss sich das Problem irgendwann mit der 2.0 eingeschlichen haben oder durch den Admin5 oder JS Controller 3!
![radar2_3](https://user-images.githubusercontent.com/18654629/129191177-43a1a386-f840-4285-904b-95cf6a631bb0.JPG)

**Comment by frankjoke** [comment]
Habe die konfig grad auf alte Version zurückgesetzt (V 2.0.0), leider ist bei js-controller >=3.1 die neue Konfig nicht mehr lauffähig und ich muss sie umbauen (in den nächsten Wochen)....

**Comment by biker1602** [comment]
Das wäre schön, wenn du sie wieder auf die neue Version umbauen würdest denn die fand ich sehr gut. 
Es ist aber schon schön, dass die alte Version wieder funktioniert.

**Comment by Roellen** [comment]
Ich hab das gleiche Problem. 
Mein geliebter Radar-Adapter ist für mich bisher das einzigste was geil funktioniert für eine Anwesenheitserkennung. 
Was muss ich genau tun um den wieder mit dem letzten Iobroker Update ans laufen zu bekommen? 
Nochmal neu installieren den Adapter?

**Comment by manoloxxl** [comment]
Ich habe gesehen, es scheint ein 2.0.3 im zu geben, hast das schon jemand versucht? 

Das gute ist, das Teil läuft wenn es vorher auch lief. Nur Änderungen gehen halt nicht.

**Comment by Roellen** [comment]
Yeah... ich hab die 2.0.3 installiert und alles läuft wieder wieder einwandfrei. Mega!

**Comment by urdl** [comment]
> Ich habe gesehen, es scheint ein 2.0.3 im zu geben, hast das schon jemand versucht?
> 
> Das gute ist, das Teil läuft wenn es vorher auch lief. Nur Änderungen gehen halt nicht.

Wo kann ich den herunterladen?
im Latest habe ich nichts gefunden 😥
