### ISSUE TITLE
Syslog "promiscuous mode"

### ISSUE THREAD

**Issue by aSilentSniper** [iobroker-community-adapters/ioBroker.radar2#125]
**Describe the bug**  
Syslog is Spammed with `Jan 23 21:29:18 iobroker kernel: [1339639.418875] device eth0 left promiscuous mode`
The syslog is getting so big it fills my entire root partition

**To Reproduce**  
1. I have no idea i just installed the adapter
2. If i stop the adapter the messages stop

**Expected behavior**  
Dont fill my pi up

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/3136108/214143236-8232d954-ce46-413b-8a94-73b421f73c9c.png)

**Versions:**  
 - Adapter version: <2.0.3>
 - JS-Controller version: <4.0.24> 
 - Node version: <16.19.0> 
 - Operating system: <Raspbian GNU/Linux 11>

**Additional context**

**Comment by Apollon77** [comment]
In fact the adapter is scanning the network and so it needs that ... if this is an issue maybe check in google for options ... 

like https://forum-raspberrypi.de/forum/thread/41294-device-eth0-left-promiscuous-mode/

I  have no idea how to change that logging. Sorry
