### ISSUE TITLE
CPU Auslastung steigt kontinuierlich an. 

### ISSUE THREAD

**Issue by haahne** [iobroker-community-adapters/ioBroker.radar2#126]
Hallo,
die CPU Auslastung steigt bei mir Kontinuierlich an. 
Erst ein Neustart bringt die Prozessorlast wieder auf ein Normales Level.
![Screenshot_2023-01-28-01-23-43-583_dev reimu proxmon](https://user-images.githubusercontent.com/120421080/215308332-f310ef64-110d-4cfe-8261-11ac7b11f8f7.jpg)

**Comment by Apollon77** [comment]
Welche Version? Das problem sollte nur in dern 2.0.4 bestanden haben ... ab 2.0.5 sollte es weg sein.

**Comment by Apollon77** [comment]
Bitte mal latest /2.0.7 installieren ist es damit weg?
