### ISSUE TITLE
In 1.8.22 and 1.8.23 all my Xiaomi Switched stopped working

### ISSUE THREAD

**Issue by MartinSchlender** [iobroker-community-adapters/ioBroker.radar2#168]
When clicking a switch the "click", "double" click ect. events don´t fire. But I see that the switches are connected because the msg_from_zigbee and link_quality become highlighted in green (screenshot)

If I downgrade to 1.8.21 everything works fine again.

<img width="1284" alt="image" src="https://github.com/iobroker-community-adapters/ioBroker.radar2/assets/69381774/394becdd-ac72-4682-894c-2a3a95404650">

**Versions:**  
 - Adapter version: 1.8.23
 - JS-Controller version: 4.0.24
 - Node version: v18.17.0
 - Operating system: raspi mit linux

**Comment by Apollon77** [comment]
Is this correctl created on radar2 Repo? Seems not
