### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dome2075** [iobroker-community-adapters/ioBroker.radar2#19]
Hi my Radar2 Adapter always stops after starting with following errors:

host.iobroker | 2019-09-08 12:49:33.157 | info | Restart adapter system.adapter.radar2.0 because enabled
-- | -- | -- | --
host.iobroker | 2019-09-08 12:49:33.157 | error | instance system.adapter.radar2.0 terminated with code null ()
host.iobroker | 2019-09-08 12:49:33.157 | warn | instance system.adapter.radar2.0 terminated due to SIGSEGV
radar2.0 | 2019-09-08 12:49:32.807 | info | radar2 initialization started...
radar2.0 | 2019-09-08 12:49:32.744 | info | starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.radar2, node: v8.16.1

What i'm doing wrong?

thanks for help

Dominik

**Comment by Pendora2017** [comment]
Bei mir hat sich der SIGSEGV Fehler abgestellt, nachdem ich beim RaspberryPi in dem OS unter Config (dietpi-config / alternativ Raspbian: raspi-config) das Bluetooth Device aktiviert hatte. Dort war es nämlich noch ausgeschaltet obwohl ich die benötigten APT Pakete von Radar2 installiert hatte.
Vielleicht hilft dir das ja auch.
