### ISSUE TITLE
nach JS Update auf 2.0.10: No geo location data found configured in admin to calculate UWZ AREA ID or ID not valid!

### ISSUE THREAD

**Issue by MarkSau** [iobroker-community-adapters/ioBroker.radar2#22]
Nach dem Update von JS-Controller auf 2.0.10 kommt folgenden Meldung
No geo location data found configured in admin to calculate UWZ AREA ID or ID not valid!

**Comment by Apollon77** [comment]
But has nothing to do with controller 2.0 I think ... because for me it works with controller 2.0 well in general with 1.0.7 ... I check the differences

**Comment by Apollon77** [comment]
hm ... this could be because the very last commit ... https://github.com/frankjoke/ioBroker.radar2/commit/803647663fcb25a5f89041ca1b813f0069f0998b ... and could also be fixed by https://github.com/frankjoke/myAdapter/pull/1/files

**Comment by Pendora2017** [comment]
Der Fehler hat sich bei mir erledigt, nachdem ich im ioBroker Admin Panel meine Geo Location eingetragen (Land, Stadt, Breiten & Längengrad) und anschließend die Radar2 Instanz neu gestartet habe.
