### ISSUE TITLE
V1.2.0_Nach Umstellung von Noble auf Lescan keine Hersteller mehr unter radar2.0._uBTs

### ISSUE THREAD

**Issue by MarkSau** [iobroker-community-adapters/ioBroker.radar2#23]
![image](https://user-images.githubusercontent.com/22911084/65698238-7c732c00-e07c-11e9-8a52-c3fbcc394254.png)

waren vorher zu sehen

**Comment by Apollon77** [comment]
liegt es an controller 2.0 oder an einer anderen radar2 Version?

**Comment by Apollon77** [comment]
Und was genau war die Umstellung?

**Comment by MarkSau** [comment]
Update: Fehler tritt dann auf, wenn von Noble auf Lescan umgestellt wird.
Mit Noble:
![image](https://user-images.githubusercontent.com/22911084/66480349-c6a5d580-ea9e-11e9-8ed9-512915af6905.png)
Mit Lescan:
![image](https://user-images.githubusercontent.com/22911084/66480497-2308f500-ea9f-11e9-8914-39a279522858.png)
