### ISSUE TITLE
instance system.adapter.radar2.0 already running

### ISSUE THREAD

**Issue by klotzma** [iobroker-community-adapters/ioBroker.radar2#25]
Des öfteren, nach Änderung der Konfiguration kommt nachfolgende Fehlermeldung und der Adapter bleibt auf Rot.

Manuelles killen des Prozesses ist auch nicht möglich, konnte von @Apollon77 nachgestellt werden.

Adapter läuft erst wieder nach neustart des kompletten Systems.

```
host.iobroker	2019-11-15 19:35:25.343	warn	instance system.adapter.radar2.0 already running with pid 2761
host.iobroker	2019-11-15 19:35:23.840	info	stopInstance system.adapter.radar2.0 killing pid 2761
host.iobroker	2019-11-15 19:35:22.840	info	stopInstance system.adapter.radar2.0 send kill signal
host.iobroker	2019-11-15 19:35:22.838	info	stopInstance system.adapter.radar2.0 (force=false, process=true)
host.iobroker	2019-11-15 19:35:22.837	info	"system.adapter.radar2.0" enabled
host.iobroker	2019-11-15 19:35:22.218	info	stopInstance system.adapter.radar2.0 killing pid 2761
host.iobroker	2019-11-15 19:35:21.217	info	stopInstance system.adapter.radar2.0 send kill signal
host.iobroker	2019-11-15 19:35:21.215	info	stopInstance system.adapter.radar2.0 (force=false, process=true)
host.iobroker	2019-11-15 19:35:21.212	info	"system.adapter.radar2.0" 

```

**Comment by Apollon77** [comment]
bei mir kommt noch das Log das er sich beendet, aber der Prozess bleibt und beendet sich nicht. ein manuelle skillen des Prozesses geht auch!

**Comment by Pittini** [comment]
Hatte ich auch, bis ich alles so gemacht hatte wie hier beschrieben: [https://forum.iobroker.net/topic/26647/radar2-bt-already-scanning-problem](url)

Danach war dieses Problem weg, allerdings blieb das dort beschriebene Problem (bt already scanning).
