### ISSUE TITLE
Not Here Zeit zu kurz

### ISSUE THREAD

**Issue by backfisch88** [iobroker-community-adapters/ioBroker.radar2#26]
Hallo!
Habe einen Raspberry 4 mit iobroker (neuste Version) und Radar2 in Version 1.2.0

Es funktioniert prinzipiell alles hervorragend bis auf die Tatsache, dass die Geräte zu schnell als abwesend markiert werden. Habe mal zum Testen auf 75 Minuten gesetzt. Also nicht anwesend werden sie aber vielleicht nach 5 Minuten gesetzt!

Bekomme in log nur die Fehlermeldung 
No geo location data found configured in admin to calculate UWZ AREA ID or ID 

Was ja mit Zeit auf alle Fälle zu tun hätte. Zeitzone und Uhrzeit ist natürlich konfiguriert. 

Ideen?

Vielen Dank!

**Comment by ozboss** [comment]
Ich habe genau das gleiche Problem

**Comment by Pittini** [comment]
Wenn Ihr diese Fehlermeldung habt: "No geo location data found configured in admin to calculate UWZ AREA ID or ID" - dann liegt das daran dass Ihr den Adapter nicht gepatcht habt aber den JS Controller 2.x benutzt. Lösung sollte sein:

`cd /opt/iobroker/node_modules/iobroker.radar2/node_modules/@frankjoke/myadapter/
mv myAdapter.js myAdapter.bakup
wget -O myAdapter.js https://forum.iobroker.net/assets/uploads/files/1570619515405-myadapter.js`

**Comment by backfisch88** [comment]
Werde ich gleich ausprobieren, wenn ich daheim bin :)

**Comment by backfisch88** [comment]
Also

Fehlermeldung weg...
Problem weiterhin das gleiche. Hab jetzt mal getestet und 200!!!! Minuten eingestellt. Nach ca 3 Minuten ging der Switch auf false

**Comment by backfisch88** [comment]
Nochmal probiert jetzt nach vielleicht 50 Sekunden 

Also es ist einfach seltsam. 
Hab nochmal den Adapter installiert (also 2 Module). Einmal nur Bluetooth und einmal nur wlan. Es ist bei beiden exakt das gleiche Phänomen
