### ISSUE TITLE
MyIP error

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.radar2#29]
```
MyIP Error Error: Request Failed. Status Code: 522at ClientRequest.fun (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@apollon/frankjoke-myadapter/myAdapter.js:985:35)at Object.onceWrapper (events.js:286:20)at ClientRequest.emit (events.js:198:13)at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)at Socket.socketOnData (_http_client.js:442:20)at Socket.emit (events.js:198:13)at addChunk (_stream_readable.js:287:12)at readableAddChunk (_stream_readable.js:268:11)at Socket.Readable.push (_stream_readable.js:223:10)
```

... since 24.12.2019

**Comment by Apollon77** [comment]
it seems they have problems or added cloudflare ddos protection logic

**Comment by Pendora2017** [comment]
Bei mir aktuell das Gleiche:

`

radar2.0 | 2020-01-15 13:11:45.662 | info | (1867) New external IP address 0
-- | -- | -- | --
radar2.0 | 2020-01-15 13:11:45.196 | info | (1867) MyIP Error Error: Request Failed. Status Code: 522at  ClientRequest.fun  (/opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:977:35)at  Object.onceWrapper (events.js:286:20)at ClientReq

`

**Comment by Apollon77** [comment]
Scheinbar passiert das wenn der Dienst überlastet ist
