### ISSUE TITLE
Node 20.16 keine Funktion

### ISSUE THREAD

**Issue by Robbi12** [iobroker-community-adapters/ioBroker.radar2#299]
Hallo. Mit upgrade auf die neue 20.16 bleibt der Adapter zwar grün, erkennt aber keine Änderung der Anwesenheitswerte

**Comment by mcm1957** [comment]
Bitte bei jedem Issue die beteiligten Versionen vollständig angeben:

adapter
js-controller
aadmin
node 
O/S

Und bitte ein Log mit Level DEBUG anhängen

**Comment by Apollon77** [comment]
@Robbi12 Am Adapter ist seit ewig nichts geändert worden, keine weiteren bBerichte. Ich würde sagen Log bitte und vorher mal die Fritzbox neu starten

**Comment by Robbi12** [comment]
Hallo. Ich kann keinen Fehler finden. Jedoch meldet er meine Handys nicht mehr auf true.

Ich habe jetzt eine Lösung gefunden. Adapter deinstalliert. Dann neu installiert. Nun funktioniert es. Nur ein update auf die neues node hatte nicht funktioniert. Auch kein restart der Instanz

**Comment by mcm1957** [comment]
Ok
Dann kann man hier mal closen.

Danke f Feedback.
