### ISSUE TITLE
BT unknown Einträge unterbinden

### ISSUE THREAD

**Issue by Redclaw88** [iobroker-community-adapters/ioBroker.radar2#31]
Gibt es ne Möglichkeit die unknown Einträge für BT zu unterbinden?
Hintergrund: Bei mir in der Gegend ist viel Verkehr und es werden innerhalb einer Woche bis zu 16000 unknown Einträge generiert und überwacht. Das verlangsamt das System beträchtlich.
Jede MAC einzeln eingeben erscheint mir dann doch etwas übertrieben. Ich Persöhnlich überwache nur 2 oder 3 BT Adressen.

**Comment by razio80** [comment]
Das wäre super, da auch bei mir unendlich viele DP angelegt werden

**Comment by RoFrie** [comment]
Eine Lösung dafür wäre schon hilfreich. Ich hatte schon mal 100.000 Einträge! Dann ist IoBroker nicht mehr zu gebrauchen

**Comment by frankjoke** [comment]
Ok, schau mir das an, eine neue Option im Config wird notwendig.

**Comment by RoFrie** [comment]
Klasse. Vielen Dank.

**Comment by sreevo** [comment]
eine sehr gute idee

**Comment by HolgerOnGithub** [comment]
ich würde das auch sehr Beführworten. mir ist schon zweimal der komplette ioBroker wegen der überfüllten Datenbank "gestorben"

**Comment by asmitconsulting** [comment]
Ich würde auch gern das Sammeln der unbekannten Geräte abschaltbar haben. Hat auch bei mir schon die GUI zum aufhängen gebracht, wenn ich den _uBT-Ordner öffne
