### ISSUE TITLE
adapter.objects.getObjectList is deprecated

### ISSUE THREAD

**Issue by ghost** [iobroker-community-adapters/ioBroker.radar2#43]
(15018) adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!

**Comment by frankjoke** [comment]
Can you try to load latest version from git, it has same version number but should use new library from ioBroker which should not produce this error.

**Comment by Voodoo2man** [comment]
After installing the github version I get this error:

18606) Adapter Error, stop: TypeError: Cannot read property 'bind' of undefined at Function.initAdapter (/opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:252:65) at /opt/iobroker/node_mod

**Comment by Pocky007** [comment]
Schön das Du wieder da bist.
Wenn ich Update kommt dieses:
`
2020-04-21 18:55:11.526  - [31merror[39m: radar2.0 (20440) Adapter Error, stop: TypeError: Cannot read property 'bind' of undefined at Function.initAdapter (/opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:252:65) at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:383:63 at processTicksAndRejections (internal/process/task_queues.js:97:5)
--


`

**Comment by MarkSau** [comment]
den myAdapter.js:252 hatte ich bis eben auch...habe die Version von github frankjoke/myAdapter drüber kopiert....dann ging alles wieder..ok., der fehler adapter.objects.getObjectList is deprecated ist dann auch noch da,,,

**Comment by frankjoke** [comment]
Ok, muss mir das näher anschauen, auf meiner test/development-VM funktionierts.
adapter.objects.getObjectList wird durch js-controller 2+ nicht mehr unterstützt und ich habe es in myAdapter geändert ( myAdapter hat aus dem alten getObjectList eine Async-Version gebaut). Egal, das neue 'bind'-Problem bedeutet vielleicht das ein anderer alter adapterlink auch nicht mehr unterstützt wird...

**Comment by Pocky007** [comment]
Schau Dir mal den myAdapter an.
Da wurde bereits mal ein Fix für myAdapter gemacht.
`cd /opt/iobroker/node_modules/@frankjoke/myadapter/
sudo mv myAdapter.js myAdapter.bakup
wget -O myAdapter.js https://forum.iobroker.net/assets/uploads/files/1570619515405-myadapter.js
Mit diesem Fix ist meine oben genannter Fehler weg.
Dafür aber noch der Überschrift Fehler dieses issues.
Vieleicht  `verknüpfst´ Du beide Versionen?

`

**Comment by frankjoke** [comment]
Ok, hab mir den Adapter angeschaut, habe nicht nur im myAdapter sondern auch in Radar2 Änderungen vorgenommen (momentan nur auf Git). kannst beides von Git laden? Ich habe auch bei radar2 die package.versionen auf die letzten hochgezogen damit es sich nicht spießt.
Bei mir funktionierts jetzt zumindest...

**Comment by Voodoo2man** [comment]
Habe gerade die Neue Radar2 Version von Github installiert. Fehler tritt immernoch auf.
Muss man myadapter dafür separat installieren?

21581) Adapter Error, stop: TypeError: Cannot read property 'bind' of undefined at Function.initAdapter (/opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:252:65) at /opt/iobroker/node_mod

**Comment by frankjoke** [comment]
I updated version numbers on git to get both new files loaded...

**Comment by MarkSau** [comment]
eine update vom git ergibt den gleichen Fehler.
Adapter Error, stop: TypeError: Cannot read property 'bind' of undefined at Function.initAdapter (/opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:252:65) at /opt/iobroker/node_mod
Wenn ich die runtergeladenen Dateien myadpter.js und package.json dann manuell via scp in /opt/iobroker/node_modules/@frankjoke/myadapter/ kopiere startet Radar2 wieder, habe dann allerdings den .getObjectList is deprecated wieder.

**Comment by MarkSau** [comment]
so...habe mal getestet...wenn ich die Dateien /opt/iobroker/node_modules/@frankjoke/myadapter/ umbenenne und diese somit nicht mehr verfügbar sind, startet Radar2 wieder. Es kommt zwar der bekannte Fehler, aber es läuft. Werden die Dateien überhaupt benötigt?Denn ohne läuft es ja...

**Comment by frankjoke** [comment]
Verwendet ihr JS-controller 3?
Mein Testsystem war ein 32-bit-stretch-intel mit node V 10.x .
Habe mir heute auf meinem QNAP eine 64-bit debian-Buster-Server VM generiert (es hat allerdings einige Zeit gedauert bis isch die fehlenden packages zum Rapi-buster gefunden und installiert hatte). Egal, auch dann nodejs 12 installiert und natürlich ioBroker! Das Ding geht (als 2CPU-VM mit 1GB memory) sauschnell im Vergleich zum Raspi wo es noch kein offizielles 64-bit gibt... (Nodejs/Chrome- debugger geht nicht alles mit 32 bit)...
Nun jetzt tritt der Fehler auch wieder `Cannot read property 'bind' of undefined at Functi...`.
Auf V10 und js-controller 2.x gings aber jetzt kann ich zum Testen auf V3 anfangen., muss mir nur noch die debug-Umgebung und repos installieren.....

**Comment by MarkSau** [comment]
ich ja..node 12.16 und JS 3.0.14

**Comment by Pocky007** [comment]
Hier auch Node 12 und JS Controller 3.X

**Comment by frankjoke** [comment]
Ok, hab's glaub ich gefunden: Der neue "@iobroker/adapter-core": "^2.3.x" (für js-con 3 notwendig) hat die Funktion getObjectList von adapter.objects auf adapter verschoben!
Deshalb gings zwar auf js-con V2.x aber nicht mehr bei V3!
Hab jetzt eine Abfrage eingebaut damit es auf beiden funktionieren soll!
Bitte neuen (1.2.6) myAdapter installieren!

**Comment by frankjoke** [comment]
p.s.: IIch habe einen neuen Drucker gebraucht und gesehen dass radar2 den neuen nicht verstandan hat, hab deshalb auch dieses Problem gelöst und in der neuen radar2 v1.2.3 korrigiert, momentan nur auf git!

**Comment by Pocky2507** [comment]
@frankjoke 
Sieht gut aus. Keine Fehlermeldungen mehr zu sehen.
In MyAdapter steht allerdings noch eine alte Version drin: 1.2.5+ April

**Comment by foxriver76** [comment]
In controller 4 this warning will throw, so could you please ensure, that it gets fixed and create a new release. You can simply replace https://github.com/frankjoke/ioBroker.radar2/blob/f3708e9b72a62fe4aba49142e387ba8d5b95d9f9/fjadapter-core.js#L327 by `adapter.getObjectList`
