### ISSUE TITLE
 Object xxxxxxxx is invalid: This object will not be created in future versions.

### ISSUE THREAD

**Issue by darkman242** [iobroker-community-adapters/ioBroker.radar2#45]
Hallo, ich habe auf die aktuelle Version von Github aktualisiert und bekomme nachfolgende Fehlermeldung im ioBroker-Log.
`
radar2.0 | 2020-04-27 06:26:40.150 | warn | (20525) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
radar2.0 | 2020-04-27 06:26:40.149 | warn | (20525) Object Michael-Handy_BT._here is invalid: obj.common.type has an invalid value (undefined) but has to be one of number, string, boolean, array, object, mixed, file, json
radar2.0 | 2020-04-27 06:26:40.144 | warn | (20525) This object will not be created in future versions. Please report this to the developer.
radar2.0 | 2020-04-27 06:26:40.144 | warn | (20525) Object Michael-Handy_BT is invalid: obj.common.type has an invalid value (undefined) but has to be one of number, string, boolean, array, object, mixed, file, json

`

**Comment by FRYYYYYY** [comment]
Hier auch!

**Comment by frankjoke** [comment]
Ok, schau mir das bei nächster Gelegenheit an!  Die neuen js-controller-Versionen sind etwas pingelinger geworden als sie vor einem Jahr waren :)!

**Comment by Diginix** [comment]
Erhalte auch für alle BT Geräte diese Logmeldungen bei Adapterstart.
`
radar2.0 | 2020-05-04 09:34:39.347 | warn | (386673) Object BH100._here is invalid: obj.common.type has an invalid value (undefined) but has to be one of number, string, boolean, array, object, mixed, file, json
-- | -- | -- | --
radar2.0 | 2020-05-04 09:34:39.339 | warn | (386673) This object will not be created in future versions. Please report this to the developer.
radar2.0 | 2020-05-04 09:34:39.338 | warn | (386673) Object BH100 is invalid: obj.common.type has an invalid value (undefined) but has to be one of number, string, boolean, array, object, mixed, file, json
radar2.0 | 2020-05-04 09:34:39.292 | warn | (386673) This object will not be created in future versions. Please report this to the developer.

`
