### ISSUE TITLE
timeout value for detecting device as offline is ignored

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.radar2#48]
I have set the timeout in instance settings to 5 minutes after which a device is detected as offline.
But already after 2 minutes after "_lastHere" the state "_here" will be set to "false".

adapter version: 1.2.0 and 1.2.3
nodejs 10.20.1
JS-Controller 1.x, 2.x and 3.0.20

**Comment by frankjoke** [comment]
Will check that later, when I have moved my development system completely because I need to debug that case.

**Comment by FRYYYYYY** [comment]
That would explain why my house has been going crazy since update and keeps locking us in.

**Comment by darkman242** [comment]
Das Problem ist [hier](https://forum.iobroker.net/topic/19794/adapter-neuer-radar2-adapter/735) schon aufgetaucht und zumindest ein Workaround gefunden.

**Comment by frankjoke** [comment]
Ok, hab mir das angeschaut aber noch keine Lösung gefunden.
Der Adapter versucht anhand des letzten heres herauszufinden wann der state zuletzt upgedated wurde und wenn er den state findet dann verwendet er lasthere von dann, aber wenn er ihn nicht findet berechnet er ein neues lasthere das nur kurz in der Vergangenheit liegt.
Das sollte eigentlich nur greifen wenn der Adapter frisch installiert wurde oder dies attes gelöscht wurden!

**Comment by FRYYYYYY** [comment]
Ich habe den Adapter erst einmal deaktiviert, weil sich die Tür hier zwischendurch einfach abschließt. :-)

**Comment by Diginix** [comment]
Auch mit dem Bug lässt er sich nutzen. Ich habe einfach ein Skript mit einer eigenen Hysterese und eigenen Objekten von denen ich dann weitere Steuerungen abhängig mache. Das lässt sich schon workarounden.

**Comment by FRYYYYYY** [comment]
Ja, das stimmt. Aber mir fehlt jetzt auch die Zeit für einen Workaround. :-)

**Comment by Speedbreaker12** [comment]
> 
> 
> Ok, hab mir das angeschaut aber noch keine Lösung gefunden.
> Der Adapter versucht anhand des letzten heres herauszufinden wann der state zuletzt upgedated wurde und wenn er den state findet dann verwendet er lasthere von dann, aber wenn er ihn nicht findet berechnet er ein neues lasthere das nur kurz in der Vergangenheit liegt.
> Das sollte eigentlich nur greifen wenn der Adapter frisch installiert wurde oder dies attes gelöscht wurden!

Ich glaub du suchst den Fehler an der falschen Stelle. Ich glaub er übernimmt die Einstellungen einfach nicht. Bei mir steht Wie lange (in Minuten) sollte ein Gerät nicht erkannt wird, bevor es markiert als Weg' (>=1): auf 6 Minuten!
Wenn der Adapter startet sagt er aber:
(14378) radar2 set to flag items away if they are not seen for 1 minutes

**Comment by FRYYYYYY** [comment]
> Ich hab sie auskommentiert und alles funktioniert wieder normal.
> Falls jemand meine Version als Workaround installieren möchte bis frankjoke den Fehler gefixed hat:
> https://github.com/Speedbreaker12/ioBroker.radar2/

Danke @Speedbreaker12 , klappt perfekt.

**Comment by frankjoke** [comment]
@Speedbreaker12 ,
Ich habe den Fehler schon gefunden und habe momentan eine neue Testversion auf einem neuen branch `newV2` erzeugt. habe dort etliche andere Änderungen auch vorgenommen (ist beta von 2.0 Version).
Muss noch einiges fertigstellen und dann readme's u.s.w ändern. 

über `https://github.com/frankjoke/ioBroker.radar2/tarball/newV2` kann die Version (steht auf 1.99) in den iobroker geladen werden. Sobald ich mehr Tester brauche werd ich diese Beta im Forum präsentieren.
