### ISSUE TITLE
Vorschlag Adapter änderung (wirklich online?)

### ISSUE THREAD

**Issue by sreevo** [iobroker-community-adapters/ioBroker.radar2#53]
hey frank, 
du hast ja die funktion im radar2 drin, dass wenn man die verbindung verliehrt (in der eingestellten zeit) die anwesenheit auf false gesetzt wird.

kannst du auch eine einstellungs möglichkeit geben, die in einer bestimmten zeit abfragt ob jemand online kommt.

wenn ich zb zur garage gehe und ich schon als false angezeigt werde, ich aber denn mit dem auto am haus vorbei fahre und er mich wieder scannt, stellt er mich wieder auf online obwohl ich nur einen kurzen moment im radius war. 

gut wäre eine weitere abfrage (zeit einstellungs möglichkeit) ob ich wirklich online bin und er denn erst auf true stellen würde.

das problem ist auch nicht gelöst, wenn ich einfach die verzögerung der abfrage auf 1-2 minuten stelle (zudem es ziemlich langsam wäre). wenn ich in dieser abfrage zeit vor dem haus vorbei fahre, stellt er mich ja trotzdem auf true.

mfg

**Comment by frankjoke** [comment]
Momentan ist das nicht vorgesehen, werde aber mal schauen ob es möglich ist sowas einzubauen OHNE die andere Logik zu beeinflussen.
