### ISSUE TITLE
Read-only state "xxxxx.state" has been written without ack-flag

### ISSUE THREAD

**Issue by bendigbjoern** [iobroker-community-adapters/ioBroker.radar2#76]
Since update Admin5 and controller 3.3.2 the following problem flooding the log

https://ibb.co/HY0M0Tf

Is there anything what is to do? Or have we wait for an update that will fix that issue?

**Comment by Pittini** [comment]
> Since update Admin5 and controller 3.3.2 the following problem flooding the log

With Controller 3.3.x you are using an Beta-Version from latest repo. So, dont wonder if there occur strange things.

**Comment by FRYYYYYY** [comment]
Workaround:

```
cd /opt/iobroker
npm i iobroker.js-controller@3.2.16 --production
```

**Comment by frankjoke** [comment]
I know about probloem as well already, a new version of the adapter will be available (not before end of the month) to resolve this and other issues introduced by more stringent checks at new js-controller and admin versions.

Anyhow, you don't need to step back on js-controller, it's just a warning which do not affect operation! 
You may set log level of adapter to `error` to avoid them in log.

**Comment by TA2k** [comment]
@frankjoke  
I add the ack to all setStates in this PR. Now the adapter works aligned to the ioBroker specification

https://github.com/frankjoke/ioBroker.radar2/pull/86

**Comment by TA2k** [comment]
If the PR is not merged you can temporary install from the forked repo

**Comment by TA2k** [comment]
@frankjoke Can you please temporary merge my PR?

**Comment by Speedbreaker12** [comment]
@TA2k I took your repository, fixed the wrong type errors and created a new pull request,

**Comment by TA2k** [comment]
Nice but will it ever merge? we will see

**Comment by Speedbreaker12** [comment]
> 
> 
> Nice but will it ever merge? we will see

I guess not :)
