### ISSUE TITLE
Fehler und Beenden des Adapters

### ISSUE THREAD

**Issue by Sefina-DS** [iobroker-community-adapters/ioBroker.radar2#78]
Nach dem Updaten des IOBrokers auf Version :

Node.js v12.22.1
NPM 6.14.12

Beendet sich der Adapter sofort.
Adapter wurde deinstalliert und neuinstalliert auf Version 2.0.1 und 3 IP Adressen wurden eingetragen.
Bluetooth währe als nächstes dran (Bluetooth geht bereits) (ging auch vorher)

Logs sind angehangen.

![fehler2](https://user-images.githubusercontent.com/35521885/117114357-08d2ee00-ad8c-11eb-8a3e-821dff4ec871.PNG)

**Comment by timtaylorrr** [comment]
Bitte führe das nochmal aus. Das hat bei mir funktioniert.

sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip $(eval readlink -f `which arp-scan`)
sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip $(eval readlink -f `which node`)
sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip $(eval readlink -f `which arp`)
sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip $(eval readlink -f `which hcitool`)
sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip $(eval readlink -f `which hciconfig`)
sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip $(eval readlink -f `which l2ping`)
