### ISSUE TITLE
Geräte können nicht hinzugefügt werden

### ISSUE THREAD

**Issue by Wurzeldoktor** [iobroker-community-adapters/ioBroker.radar2#81]
Version 2.0.1
host:3.3.8

leider ist es mir absolut nicht möglich neue Geräte hinzuzufügen.
wenn ich unten rechts in der Instanz auf hinzufügen klicke, passiert mal gar nichts.

Leider gingen mir vor kurzen Aufgrund eines komplet crash alle Daten verloren, seit dem neu aufsetzen - kein hinzufügen von geräten mehr möglich?!

Installation lt Anleitung.

**Comment by philipphunger** [comment]
Habe das gleiche Problem, außerdem lassen sich keine Einstellungen speichern.

Version 2.0.1

**Comment by shepart** [comment]
Same issue here (cannot save)!

**Comment by Wurzeldoktor** [comment]
leider nach wie vor, absolut keine Reaktion der Programmierer :( Schade

**Comment by philipphunger** [comment]
Der Entwickler hat in einem anderen Issue schon darauf hingewiesen dass er nächsten Monat ein Update bringen will. Nicht jeder arbeitet vollzieht an seinen Projekten.

**Comment by Peter1980FFM** [comment]
Leider ein Generelles Problem, daher ist der Adapter derzeit unbrauchbar für alle hatte gehofft eine Adaper gefunden zu haben der bisher am Besten funktioniert hat

**Comment by Peter1980FFM** [comment]
habe jetzt so lange gespielt hier nun ein Workaround:
1.) Instanz löschen. (optional)
2.) Entwickleroptionen im IOBroker Aktivieren
3.) Version 1.25 Installieren (downgraden kann auch Funktionieren)
4.) Einstellungen vornehmen
5.) Upgrade auf 2.01 vornehmen
6.) Keine Einstellungen im Adapter vornehmen

Ist zwar Blöd, aber so kann man wenigstens Änderungen durchführen...
Jedoch wäre der entwickler gut Beraten die Version 2 zurückzuziehen

**Comment by Wurzeldoktor** [comment]
> habe jetzt so lange gespielt hier nun ein Workaround:
> 1.) Instanz löschen. (optional)
> 2.) Entwickleroptionen im IOBroker Aktivieren
> 3.) Version 1.25 Installieren (downgraden kann auch Funktionieren)
> 4.) Einstellungen vornehmen
> 5.) Upgrade auf 2.01 vornehmen
> 6.) Keine Einstellungen im Adapter vornehmen
> 
> Ist zwar Blöd, aber so kann man wenigstens Änderungen durchführen...
> Jedoch wäre der entwickler gut Beraten die Version 2 zurückzuziehen

Hey danke für die Anleitung und den Versuch :)

Ich selbst werde mir die mühen aber ned antun 😅 
Werde weiter nach alternativen suchen. Evtl wenn ich mal zeit habe, den PING Adapter versuchen.
