### ISSUE TITLE
Error {} is setState for....

### ISSUE THREAD

**Issue by crunchip77** [iobroker-community-adapters/ioBroker.radar2#93]
Admin v 5.1.22
JS controller v3.3.15
radar2 v2.0.2
folgende Meldung erscheint nachdem die Instanz per cron neu gestartet wird
`

radar2.0 | 2021-08-05 00:03:00.754 | warn | Error {} is setState for _uIPs with {"val":"[]","ack":true,"from":"system.adapter.radar2.0","user":"system.user.admin"}
-- | -- | -- | --
radar2.0 | 2021-08-05 00:03:00.752 | warn | get state error: Connection is closed.
radar2.0 | 2021-08-05 00:03:00.750 | warn | Could not perform strict object check of state radar2.0._uIPs: Connection is closed.
radar2.0 | 2021-08-05 00:03:00.748 | warn | Error {} is setState for _uBTs with {"val":[],"ack":true,"from":"system.adapter.radar2.0","user":"system.user.admin"}
radar2.0 | 2021-08-05 00:03:00.741 | warn | get state error: Connection is closed.
radar2.0 | 2021-08-05 00:03:00.740 | warn | Could not perform strict object check of state radar2.0._uBTs: Connection is closed.
radar2.0 | 2021-08-05 00:03:00.737 | warn | Error {} is setState for Noel_Cubot._nHere with {"val":766,"ack":true,"from":"system.adapter.radar2.0","user":"system.user.admin"}
radar2.0 | 2021-08-05 00:03:00.729 | warn | get state error: Connection is closed.
radar2.0 | 2021-08-05 00:03:00.727 | warn | Could not perform strict object check of state radar2.0.Noel_Cubot._nHere: Connection is closed.
radar2.0 | 2021-08-05 00:03:00.656 | warn | Error {} is setState for Galaxy-S10._nHere with {"val":90,"ack":true,"from":"system.adapter.radar2.0","user":"system.user.admin"}

`

**Comment by biker1602** [comment]
Wird an dem Adapter denn gearbeitet? Es ist schon so lange nichts passiert dort und seit dem Update auf
Admin v 5.1.22
JS controller v3.3.15
radar2 v2.0.2

Geht leider gar nichts mehr. Es lässt sich nichts hinzufügen nichts speichern oder sonstiges. Eigentlich schade denn ich habe ihn sehr gerne genutzt z.B. für An und Abwesenheit
